exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".aws-sam",
    "layers",
    "build",
    "dist",
]

line-length = 100

target-version = "py312"

[lint]
select = ["ALL"]

ignore = [
    "D203",
    "D213",
    "PLR2004",
    "PTH",
    "EXE002",
    "E501",
    "D100",
    "D104",
    "D200",
    "D205",
    "D401",
    "T201",
    "S101",
    "COM812",
    "ISC001",
    "BLE001",
    "TRY300",
    "EM101",
    "EM102",
    "TRY003",
    "FBT001",
    "FBT002",
    "DTZ005",
    "PLR0911",
    "PGH003",
    "ANN401",
]

[lint.per-file-ignores]
"tests/*" = ["ANN001", "ANN202", "SLF001", "ARG002", "PLC0415", "D101", "D102", "D105", "D107"]
