sonar.projectKey=porteken_ai-resume-analyzer-sam
sonar.organization=porteken
sonar.coverage.exclusions=tests/**
sonar.qualitygate.wait=true

#sonar.projectName=ai-resume-analyzer-sam
#sonar.projectVersion=1.0



#sonar.sources=.


#sonar.sourceEncoding=UTF-8