sonar.projectKey=porteken_ai-resume-analyzer-sam
sonar.organization=porteken

sonar.sources=resume_analyzer
sonar.tests=tests

sonar.exclusions=**/__pycache__/**,**/venv/**,**/.venv/**,.aws-sam/**,layers/**,htmlcov/**,**/*.pyc,*.ipynb
sonar.coverage.exclusions=tests/**,**/conftest.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13

sonar.qualitygate.wait=true
